i = int(input('Digite um número inteiro: '))
print('Tabuada do {}\n {} x {} = {}'.format(i, i, 0,i*0))
print(' {} x {} = {}'.format(i, 1, i*1))
print(' {} x {} = {}'.format(i, 2, i*2))
print(' {} x {} = {}'.format(i, 3, i*3))
print(' {} x {} = {}'.format(i, 4, i*4))
print(' {} x {} = {}'.format(i, 5, i*5))
print(' {} x {} = {}'.format(i, 6, i*6))
print(' {} x {} = {}'.format(i, 7, i*7))
print(' {} x {} = {}'.format(i, 8, i*8))
print(' {} x {} = {}'.format(i, 9, i*9))
print(' {} x {:<} = {:<}'.format(i, 10, i*10))

